orbs:
  maven: circleci/maven@1.2.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test
       build:
          docker:
            - image: circleci/node:jessie-browsers
              auth:
                username: pilyav4ik
                password: $DOCKERHUB_PASSWORD  
          steps:
            - checkout
            - run: mkdir test-reports
            - run:
                name: Download Selenium
                command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
            - run:
                name: Start Selenium
                command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
                background: true